improvements

diff --git a/ghelper b/ghelper
--- a/ghelper
+++ b/ghelper
@@ -68,6 +68,10 @@ while [[ $# -gt 0 ]]; do
       GH_NO_PUSH=1
       shift # past argument
       ;;
+    -O|--no-pull-request)
+      GH_NO_PR=1
+      shift # past argument
+      ;;
     -M|--merge)
       GH_MERGE=1
       shift # past argument
@@ -106,6 +110,7 @@ done
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
 if [[ -n "$HELP" ]]; then
+  echo ""
   echo "Usage: ghelper [options] <list of git repositories>"
   echo ""
   echo "Options:"
@@ -114,9 +119,10 @@ if [[ -n "$HELP" ]]; then
   echo "  -d, --delete <file1,file2,...>                     Files to delete."
   echo "  -b, --branch-name <name>                           Name of the branch to create."
   echo "  -m, --commit-message <message>                     Commit message."
-  echo "  -c, --continue-on-missing-file                     Continue if a file to delete is missing."
+  echo "  -c, --continue-on-missing-file                     Continue even if a file to delete is missing."
   echo "  -B, --base-branch-name <name>                      Name of the base branch to create the new branch from. If not provided, the script will try to find a main branch (main, master, trunk, develop) in the repository."
   echo "  -P, --no-push                                      Do not push to origin."
+  echo "  -O, --no-pull-request                              Do not open a pull request."
   echo "  -M, --merge                                        Automatically merge pull requests. Uses merge commit by default, can be combined with --squash or --rebase."
   echo "  -S, --squash                                       Squash commits when merging pull requests."
   echo "  -R, --rebase                                       Rebase commits when merging pull requests."
@@ -175,6 +181,7 @@ if [[ -n $DEBUG ]]; then
   printf "%sCONTINUE_ON_MISSING_FILE%s: %s\n" "$UNDERLINE" "$NORMAL" "$CONTINUE_ON_MISSING_FILE"
   printf "%sGH_BASE_BRANCH_NAME%s: %s\n" "$UNDERLINE" "$NORMAL" "$GH_BASE_BRANCH_NAME"
   printf "%sGH_NO_PUSH%s: %s\n" "$UNDERLINE" "$NORMAL" "$GH_NO_PUSH"
+  printf "%sGH_NO_PR%s: %s\n" "$UNDERLINE" "$NORMAL" "$GH_NO_PR"
   printf "%sGH_MERGE%s: %s\n" "$UNDERLINE" "$NORMAL" "$GH_MERGE"
   printf "%sGH_SQUASH%s: %s\n" "$UNDERLINE" "$NORMAL" "$GH_SQUASH"
   printf "%sGH_REBASE%s: %s\n" "$UNDERLINE" "$NORMAL" "$GH_REBASE"
@@ -203,7 +210,7 @@ fi
 
 # Create working directory
 
-SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
+SCRIPT_PATH="$(pwd)"
 WORKING_DIR=$(mktemp -d)
 printf "> Creating working-directory in %s%s%s.\n" "$BLUE" "$WORKING_DIR" "$NORMAL"
 cd "$WORKING_DIR"
@@ -309,18 +316,20 @@ for GIT_REPO in $GIT_REPOS; do
   printf "   > Checking out new branch %s%s%s.\n" "$BLUE" "$GH_NEW_BRANCH_NAME" "$NORMAL"
   git checkout -b "$GH_NEW_BRANCH_NAME" -q
 
+  COMMIT_BODY="This commit was automatically generated by [ghelper](https://github.com/3lvia/ghelper)."
+
   if [[ -n "$COMMIT_MESSAGE" ]]; then
     printf "   > Committing changes, using custom commit message...\n"
-    git commit -m "$COMMIT_MESSAGE" -q
+    git commit -m "$COMMIT_MESSAGE" -m "$COMMIT_BODY" -q
   else
     printf "   > Committing changes, using default commit message...\n"
-    git commit -m "Add and delete files" -m "Files added: $ADD_FILES" -m "Files deleted: $DEL_FILES" -q
+    git commit -m "Update files" -m "$COMMIT_BODY" -q
   fi
 
   printf "   > Changes committed.\n"
 
 
-  # Push to origin and create pull request
+  # Push to origin
 
   if [[ -n "$GH_NO_PUSH" ]]; then
     printf "   > Pushing to origin disabled.\n"
@@ -336,40 +345,50 @@ for GIT_REPO in $GIT_REPOS; do
       exit 1
     fi
 
-    printf "   > Creating pull request...\n"
-    GH_PR_CREATE_ERROR_LOG="$(mktemp)"
-    if ! GH_PR_CREATE_URL=$(gh pr create -B "$MAIN_BRANCH_FOR_REPO" -a '@me' -f 2> "$GH_PR_CREATE_ERROR_LOG"); then
-      printf "      > %sPull request creation failed:\n\n" "$RED"
-      cat "$GH_PR_CREATE_ERROR_LOG"
-      printf "%s" "$NORMAL"
-      exit 1
-    fi
 
-    printf "   > Pull request created.\n"
+    # Create pull request
 
-    if [[ -n "$GH_MERGE" ]]; then
-      printf "   > Merging pull request disabled, see pull request at %s%s%s.\n" "$BLUE" "$GH_PR_CREATE_URL" "$NORMAL"
+    if [[ -n "$GH_NO_PR" ]]; then
+      printf "   > Pull request creation disabled.\n"
     else
-      if [[ -n "$GH_SQUASH" ]]; then
-        printf "   > Pull request will be merged using squash.\n"
-        GH_MERGE_ARG="-s"
-      elif [[ -n "$GH_REBASE" ]]; then
-        printf "   > Pull request will be merged using rebase.\n"
-        GH_MERGE_ARG="-r"
-      else
-        printf "   > Pull request will be merged using merge commit.\n"
-        GH_MERGE_ARG="-m"
-      fi
-
-      printf "   > Merging pull request...\n"
-      GH_PR_MERGE_ERROR_LOG="$(mktemp)"
-      if ! gh pr merge -s -d --auto "$GH_MERGE_ARG" 2> "$GH_PR_MERGE_ERROR_LOG"; then
-        printf "   > %sPull request merge failed:\n\n" "$RED"
-        cat "$GH_PR_MERGE_ERROR_LOG"
+      printf "   > Creating pull request...\n"
+      GH_PR_CREATE_ERROR_LOG="$(mktemp)"
+      if ! GH_PR_CREATE_URL=$(gh pr create -B "$MAIN_BRANCH_FOR_REPO" -a '@me' -f 2> "$GH_PR_CREATE_ERROR_LOG"); then
+       printf "      > %sPull request creation failed:\n\n" "$RED"
+        cat "$GH_PR_CREATE_ERROR_LOG"
         printf "%s" "$NORMAL"
         exit 1
       fi
-      printf "   > Pull request merged.\n"
+
+      printf "   > Pull request created.\n"
+
+
+      # Merge pull request
+
+      if [[ -z "$GH_MERGE" ]]; then
+        printf "   > Merging pull request disabled, see pull request at %s%s%s.\n" "$BLUE" "$GH_PR_CREATE_URL" "$NORMAL"
+      else
+        if [[ -n "$GH_SQUASH" ]]; then
+          printf "   > Pull request will be merged using squash.\n"
+          GH_MERGE_ARG='-s'
+        elif [[ -n "$GH_REBASE" ]]; then
+          printf "   > Pull request will be merged using rebase.\n"
+          GH_MERGE_ARG='-r'
+        else
+          printf "   > Pull request will be merged using merge commit.\n"
+          GH_MERGE_ARG='-m'
+        fi
+
+        printf "   > Merging pull request...\n"
+        GH_PR_MERGE_ERROR_LOG="$(mktemp)"
+        if ! gh pr merge -d --auto "$GH_MERGE_ARG" 2> "$GH_PR_MERGE_ERROR_LOG"; then
+          printf "   > %sPull request merge failed:\n\n" "$RED"
+          cat "$GH_PR_MERGE_ERROR_LOG"
+          printf "%s" "$NORMAL"
+          exit 1
+        fi
+        printf "   > Pull request merged.\n"
+      fi
     fi
 
     set -e # re-enable exit on error
@@ -377,6 +396,8 @@ for GIT_REPO in $GIT_REPOS; do
 
   printf "\n"
 done
+
+# Clean up (or not)
 
 if [[ -n "$NO_CLEAN" ]]; then
   echo "> Done, not cleaning up."
